services:
  - type: web
    name: LabNearMe
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist/public
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
